# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hatio
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-github-project

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-5

functions:
  hello:
    handler: handler.hello
